name: gridlock_companion
description: "Companion remote control for Gridlock MIDI Grid Analyzer"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  web_socket_channel: ^3.0.2
  provider: ^6.1.2
  google_fonts: ^6.2.1
  wakelock_plus: ^1.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
